---
title: "Worksheet#5B_group"
author: "Cadiz, Guion, Jacildo"
date: "2024-11-20"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# 1. Select 5 categories from Amazon and select 30 products from each category. 
# Guion
```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(kableExtra)
library(rmarkdown)

makeup_url <- 'https://www.amazon.com/s?k=BLUSH+ON&rh=n%3A11058281&ref=nb_sb_noss'

session1 <- bow(makeup_url,
               user_agent = "Educational")
session1

```
```{r}
library(rvest)

amazondf1 <- data.frame()

page1 <- scrape(session1)

price1 <- page1 %>%
  html_nodes('.a-price .a-offscreen') %>% 
  html_text(trim = TRUE) %>% 
  gsub("[^0-9\\.]", "", .)

description1 <- page1 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text(trim = TRUE) %>%
  gsub("\n", "", .)

ratings1 <- page1 %>%
  html_nodes('.a-icon-alt') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

reviews1 <- page1 %>%
  html_nodes('div.a-row.a-spacing-small.review-data') %>% 
  html_text()

price1 <- price1[1:min(30, length(price1))]
description1 <- description1[1:min(30, length(description1))]
ratings1 <- ratings1[1:min(30, length(ratings1))]
reviews1 <- reviews1[1:min(30, length(reviews1))]

price1 <- c(price1, rep(NA, 30 - length(price1)))
description1 <- c(description1, rep(NA, 30 - length(description1)))
ratings1 <- c(ratings1, rep(NA, 30 - length(ratings1)))
reviews1 <- c(reviews1, rep(NA, 30 - length(reviews1)))


amazondf1 <- data.frame(
  Prices_amazon = price1,
  Descriptions_amazon = description1,
  Ratings_amazon = ratings1,
  Reviewss_amazon = reviews1,
  stringsAsFactors = FALSE
)

print(amazondf1)


```

```{r}
skincare_url <- 'https://www.amazon.com/s?k=moisturizer&rh=n%3A11060451&ref=nb_sb_noss'

session2 <- bow(skincare_url,
               user_agent = "Educational")
session2
```
```{r}
library(rvest)

amazondf2 <- data.frame()

page2 <- scrape(session2)

price2 <- page2 %>%
  html_nodes('.a-price .a-offscreen') %>% 
  html_text(trim = TRUE) %>% 
  gsub("[^0-9\\.]", "", .)

description2 <- page2 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text(trim = TRUE) %>%
  gsub("\n", "", .)

ratings2 <- page2 %>%
  html_nodes('.a-icon-alt') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

reviews2 <- page2 %>%
  html_nodes('div.a-row.a-spacing-small.review-data') %>% 
  html_text()

price2 <- price2[1:min(30, length(price2))]
description2 <- description2[1:min(30, length(description2))]
ratings2 <- ratings2[1:min(30, length(ratings2))]
reviews2 <- reviews2[1:min(30, length(reviews2))]

price2 <- c(price2, rep(NA, 30 - length(price2)))
description2 <- c(description2, rep(NA, 30 - length(description2)))
ratings2 <- c(ratings2, rep(NA, 30 - length(ratings2)))
reviews2 <- c(reviews2, rep(NA, 30 - length(reviews2)))


amazondf2 <- data.frame(
  Prices_amazon = price2,
  Descriptions_amazon = description2,
  Ratings_amazon = ratings2,
  Reviewss_amazon = reviews2,
  stringsAsFactors = FALSE
)

print(amazondf2)


```
```{r}
haircare_url <- 'https://www.amazon.com/s?k=shampoo&rh=n%3A11057241&ref=nb_sb_noss'

session3 <- bow(haircare_url,
               user_agent = "Educational")
session3
```
```{r}
library(rvest)

amazondf3 <- data.frame()

page3 <- scrape(session3)

price3 <- page3 %>%
  html_nodes('.a-price .a-offscreen') %>% 
  html_text(trim = TRUE) %>% 
  gsub("[^0-9\\.]", "", .)

description3 <- page3 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text(trim = TRUE) %>%
  gsub("\n", "", .)

ratings3 <- page3 %>%
  html_nodes('.a-icon-alt') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

reviews3 <- page3 %>%
  html_nodes('div.a-row.a-spacing-small.review-data') %>% 
  html_text()

price3 <- price3[1:min(30, length(price3))]
description3 <- description3[1:min(30, length(description3))]
ratings3 <- ratings3[1:min(30, length(ratings3))]
reviews3 <- reviews3[1:min(30, length(reviews3))]

price3 <- c(price3, rep(NA, 30 - length(price3)))
description3 <- c(description3, rep(NA, 30 - length(description3)))
ratings3 <- c(ratings3, rep(NA, 30 - length(ratings3)))
reviews3 <- c(reviews3, rep(NA, 30 - length(reviews3)))


amazondf3 <- data.frame(
  Prices_amazon = price3,
  Descriptions_amazon = description3,
  Ratings_amazon = ratings3,
  Reviewss_amazon = reviews3,
  stringsAsFactors = FALSE
)

print(amazondf3)


```
```{r}
fragrance_url <- 'https://www.amazon.com/s?k=women&rh=n%3A11056591&ref=nb_sb_noss'

session4 <- bow(fragrance_url,
               user_agent = "Educational")
session4
```
```{r}
library(rvest)

amazondf4 <- data.frame()

page4 <- scrape(session4)

price4 <- page4 %>%
  html_nodes('.a-price .a-offscreen') %>% 
  html_text(trim = TRUE) %>% 
  gsub("[^0-9\\.]", "", .)

description4 <- page4 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text(trim = TRUE) %>%
  gsub("\n", "", .)

ratings4 <- page4 %>%
  html_nodes('.a-icon-alt') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

reviews4 <- page4 %>%
  html_nodes('div.a-row.a-spacing-small.review-data') %>% 
  html_text()

price4 <- price4[1:min(30, length(price4))]
description4 <- description4[1:min(30, length(description4))]
ratings4 <- ratings4[1:min(30, length(ratings4))]
reviews4 <- reviews4[1:min(30, length(reviews4))]

price4 <- c(price4, rep(NA, 30 - length(price4)))
description4 <- c(description4, rep(NA, 30 - length(description4)))
ratings4 <- c(ratings4, rep(NA, 30 - length(ratings4)))
reviews4 <- c(reviews4, rep(NA, 30 - length(reviews4)))


amazondf4 <- data.frame(
  Prices_amazon = price4,
  Descriptions_amazon = description4,
  Ratings_amazon = ratings4,
  Reviewss_amazon = reviews4,
  stringsAsFactors = FALSE
)

print(amazondf4)


```
```{r}
oralcare_url <- 'https://www.amazon.com/s?k=toothbrush&rh=n%3A10079992011&ref=nb_sb_noss'

session5 <- bow(oralcare_url,
               user_agent = "Educational")
session5
```
```{r}
library(rvest)

amazondf5 <- data.frame()

page5 <- scrape(session5)

price5 <- page5 %>%
  html_nodes('.a-price .a-offscreen') %>% 
  html_text(trim = TRUE) %>% 
  gsub("[^0-9\\.]", "", .)

description5 <- page5 %>%
  html_nodes('.a-color-base.a-text-normal') %>% 
  html_text(trim = TRUE) %>%
  gsub("\n", "", .)

ratings5 <- page5 %>%
  html_nodes('.a-icon-alt') %>% 
  html_text() %>%
  gsub(" out of 5 stars", "", .)

reviews5 <- page5 %>%
  html_nodes('div.a-row.a-spacing-small.review-data') %>% 
  html_text()

price5 <- price5[1:min(30, length(price5))]
description5 <- description5[1:min(30, length(description5))]
ratings5 <- ratings5[1:min(30, length(ratings5))]
reviews5 <- reviews5[1:min(30, length(reviews5))]

price5 <- c(price5, rep(NA, 30 - length(price5)))
description5 <- c(description5, rep(NA, 30 - length(description5)))
ratings5 <- c(ratings5, rep(NA, 30 - length(ratings5)))
reviews5 <- c(reviews5, rep(NA, 30 - length(reviews5)))


amazondf5 <- data.frame(
  Prices_amazon = price5,
  Descriptions_amazon = description5,
  Ratings_amazon = ratings5,
  Reviewss_amazon = reviews5,
  stringsAsFactors = FALSE
)

print(amazondf5)


```
# 2. Out of the 30 products, pick 10 products and extract 20 reviews in each one which includes reviewer, date, individual rating, text review, title of review, and verified purchase.
```{r}
library(rvest)
library(dplyr)

product_urls <- c( 'https://www.amazon.com/Paris-Intense-Lightweight-Formula-Pigments/dp/B0CZTZKCJY/', #1  
  'https://www.amazon.com/LAURA-GELLER-NEW-YORK-Lightweight/dp/B0B64GX5LN/', #2
  'https://www.amazon.com/Hourglass-Unreal-Liquid-Blush-Scene/dp/B0DCXX5542/', #3
  'https://www.amazon.com/Maybelline-Lightweight-Blendable-Long-lasting-Enhancing/dp/B06XDYKJDJ/', # 4
  'https://www.amazon.com/l-f-Monochromatic-Multi-Stick-Luminous/dp/B07MWSB1Z9/', # 5
  'https://www.amazon.com/wet-wild-Effortless-Luxuriously-Cruelty-Free/dp/B082YPNTZ4/', #6
  'https://www.amazon.com/wet-wild-Effortless-Luxuriously-Cruelty-Free/dp/B082YPNTZ4/', #7 
  'https://www.amazon.com/SHEGLAM-Liquid-Makeup-Cheeks-Finish/dp/B0BN69MJ8H/', # 8
  'https://www.amazon.com/Grande-Cosmetics-Peace-Love/dp/B0DFHQHNZH/', # 9
  'https://www.amazon.com/Lamel-OhMy-Clear-Face-Powder/dp/B0CRHYWPDN/')
```
```{r}
scrape_reviews <- function(url) {
session <- bow(url, user_agent = "Educational")
review_page <- scrape(session)

product_name <- review_page %>%
html_nodes('span#productTitle') %>%
html_text() %>%
trimws()

reviewers <- review_page %>%
html_nodes('.a-profile-name') %>%
html_text()

review_dates <- review_page %>%
html_nodes('.a-size-base.a-color-secondary.review-date') %>%
html_text()
review_dates_clean <- gsub("Reviewed in [a-zA-Z ]+ on ", "", review_dates)

review_titles <- review_page %>%
html_nodes('.review-title') %>%
html_text()
review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

verified_purchase <- review_page %>%
html_nodes('span[data-hook="avp-badge-linkless"]') %>%
html_text()

review_texts <- review_page %>%
html_nodes('div[data-hook="review-collapsed"] span') %>%
html_text() %>%
trimws()

max_length <- max(
length(reviewers),
length(review_dates_clean),
length(review_titles_clean),
length(review_texts),
length(verified_purchase),
na.rm = TRUE
)

product_name <- rep(product_name, length.out = max_length)
reviewers <- c(reviewers, rep(NA, max_length - length(reviewers)))
review_dates_clean <- c(review_dates_clean, rep(NA, max_length - length(review_dates_clean)))
review_titles_clean <- c(review_titles_clean, rep(NA, max_length - length(review_titles_clean)))
review_texts <- c(review_texts, rep(NA, max_length - length(review_texts)))
verified_purchase <- c(verified_purchase, rep(NA, max_length - length(verified_purchase)))

reviews <- data.frame(
Product = product_name,
Reviewer = reviewers,
Date = review_dates_clean,
ReviewTitle = review_titles_clean,
ReviewText = review_texts,
VerifiedPurchase = verified_purchase,
stringsAsFactors = FALSE
)

return(reviews)
}

all_reviews <- lapply(product_urls, scrape_reviews)

reviews_df <- bind_rows(all_reviews)

print(reviews_df)
```
```{r}
product_urls <- c( 'https://www.amazon.com/Paris-Intense-Lightweight-Formula-Pigments/dp/B0CZTZKCJY/', #1
'https://www.amazon.com/Paris-Collagen-Anti-Aging-Moisturizer-Sunscreen/dp/B0D33ZB577/', #2
'https://www.amazon.com/Moisturizer-Hydrating-Moisturizing-Hypoallergenic-Non-Comedogenic/dp/B099N2SLT9/', #3
'https://www.amazon.com/Aveeno-Moisturizer-Lightweight-Hypoallergenic-Paraben-Free/dp/B08D9MSGVQ/', # 4
'https://www.amazon.com/CeraVe-Moisturizing-Cream-Daily-Moisturizer/dp/B00TTD9BRC/', # 5
'https://www.amazon.com/Vanicream-Moisturizer-Hyaluronic-pH-Balanced-Dermatologist/dp/B08BW46XXK/', #6
'https://www.amazon.com/AESTURA-ATOBARRIER365-Hydration-Moisturizer-Sensitive/dp/B09YDCCJBJ/', #7
'https://www.amazon.com/CeraVe-Skin-Renewing-Night-Cream/dp/B00SNPCSUY/', # 8
'https://www.amazon.com/CeraVe-Facial-Moisturizing-Lotion-Lightweight/dp/B00365DABC/', # 9
'https://www.amazon.com/LOreal-Paris-Moisturizer-Revitalift-Anti-Aging/dp/B07TYY18QX/')
```


```{r}
scrape_reviews <- function(url) {
session <- bow(url, user_agent = "Educational")
review_page <- scrape(session)

product_name <- review_page %>%
html_nodes('span#productTitle') %>%
html_text() %>%
trimws()

reviewers <- review_page %>%
html_nodes('.a-profile-name') %>%
html_text()

review_dates <- review_page %>%
html_nodes('.a-size-base.a-color-secondary.review-date') %>%
html_text()
review_dates_clean <- gsub("Reviewed in [a-zA-Z ]+ on ", "", review_dates)

review_titles <- review_page %>%
html_nodes('.review-title') %>%
html_text()
review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

verified_purchase <- review_page %>%
html_nodes('span[data-hook="avp-badge-linkless"]') %>%
html_text()

review_texts <- review_page %>%
html_nodes('div[data-hook="review-collapsed"] span') %>%
html_text() %>%
trimws()

max_length <- max(
length(reviewers),
length(review_dates_clean),
length(review_titles_clean),
length(review_texts),
length(verified_purchase),
na.rm = TRUE
)

product_name <- rep(product_name, length.out = max_length)
reviewers <- c(reviewers, rep(NA, max_length - length(reviewers)))
review_dates_clean <- c(review_dates_clean, rep(NA, max_length - length(review_dates_clean)))
review_titles_clean <- c(review_titles_clean, rep(NA, max_length - length(review_titles_clean)))
review_texts <- c(review_texts, rep(NA, max_length - length(review_texts)))
verified_purchase <- c(verified_purchase, rep(NA, max_length - length(verified_purchase)))

reviews <- data.frame(
Product = product_name,
Reviewer = reviewers,
Date = review_dates_clean,
ReviewTitle = review_titles_clean,
ReviewText = review_texts,
VerifiedPurchase = verified_purchase,
stringsAsFactors = FALSE
)

return(reviews)
}

all_reviews <- lapply(product_urls, scrape_reviews)

reviews_df <- bind_rows(all_reviews)

print(reviews_df)
```
```{r}
product_urls <- c( 'https://www.amazon.com/Olaplex-No-4-Bond-Maintenance-Shampoo/dp/B07D37PQGL/r', #1
'https://www.amazon.com/Herbal-Essences-Shampoo-Conditioner-Rose/dp/B086S4Q7JH/', #2
'https://www.amazon.com/Olaplex-No-5-Bond-Maintenance-Conditioner/dp/B07D37SBHF/', #3
'https://www.amazon.com/Wella-Invigo-Enrich-Shampoo-10oz/dp/B07PP9MXYY/', # 4
'https://www.amazon.com/Living-proof-Shampoo-Perfect-Women/dp/B0BQ3YFRC5/', # 5
'https://www.amazon.com/Nizoral-Anti-Dandruff-Shampoo-Ketoconazole-Fresh/dp/B0BP8BXZ8M/', #6
'https://www.amazon.com/Nioxin-Cleansing-Peppermint-Sensitive-Progressed/dp/B005NOPU2G/', #7
'https://www.amazon.com/Head-Shoulders-Classic-Daily-Use-Anti-Dandruff/dp/B07F38LXDM/', # 8
'https://www.amazon.com/Nutrafol-Improves-Strength-Physician-formulated-Thinning/dp/B09XS8F3P2/', # 9
'https://www.amazon.com/Biolage-Hydrasource-Hydrates-Moisturizes-Paraben-Free/dp/B00J9WZZWI/')
```


```{r}
scrape_reviews <- function(url) {
session <- bow(url, user_agent = "Educational")
review_page <- scrape(session)

product_name <- review_page %>%
html_nodes('span#productTitle') %>%
html_text() %>%
trimws()

reviewers <- review_page %>%
html_nodes('.a-profile-name') %>%
html_text()

review_dates <- review_page %>%
html_nodes('.a-size-base.a-color-secondary.review-date') %>%
html_text()
review_dates_clean <- gsub("Reviewed in [a-zA-Z ]+ on ", "", review_dates)

review_titles <- review_page %>%
html_nodes('.review-title') %>%
html_text()
review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

verified_purchase <- review_page %>%
html_nodes('span[data-hook="avp-badge-linkless"]') %>%
html_text()

review_texts <- review_page %>%
html_nodes('div[data-hook="review-collapsed"] span') %>%
html_text() %>%
trimws()

max_length <- max(
length(reviewers),
length(review_dates_clean),
length(review_titles_clean),
length(review_texts),
length(verified_purchase),
na.rm = TRUE
)

product_name <- rep(product_name, length.out = max_length)
reviewers <- c(reviewers, rep(NA, max_length - length(reviewers)))
review_dates_clean <- c(review_dates_clean, rep(NA, max_length - length(review_dates_clean)))
review_titles_clean <- c(review_titles_clean, rep(NA, max_length - length(review_titles_clean)))
review_texts <- c(review_texts, rep(NA, max_length - length(review_texts)))
verified_purchase <- c(verified_purchase, rep(NA, max_length - length(verified_purchase)))

reviews <- data.frame(
Product = product_name,
Reviewer = reviewers,
Date = review_dates_clean,
ReviewTitle = review_titles_clean,
ReviewText = review_texts,
VerifiedPurchase = verified_purchase,
stringsAsFactors = FALSE
)

return(reviews)
}

all_reviews <- lapply(product_urls, scrape_reviews)

reviews_df <- bind_rows(all_reviews)

print(reviews_df)
```
```{r}
product_urls <- c( 'https://www.amazon.com/Yara-Lattafa-Perfumes-Eau-Parfum/dp/B09C8VNWBP/', #1
'https://www.amazon.com/Victorias-Secret-Pure-Seduction-8-4oz/dp/B09V1RMFTP//', #2
'https://www.amazon.com/Calvin-Klein-ETERNITY-Eau-Parfum/dp/B00021AJ5I/', #3
'https://www.amazon.com/DKNY-Delicious-Parfum-Perfume-Spray/dp/B000E7STLQ/', # 4
'https://www.amazon.com/Victorias-Secret-Tease-3-4-Ounce/dp/B07GT42VY6/', # 5
'https://www.amazon.com/Thierry-Mugler-Eau-Parfum-Alien/dp/B08ZXY1B7H/', #6
'https://www.amazon.com/Daisy-Marc-Jacobs-Toilette-Ounce/dp/B0012RQZ72/', #7
'https://www.amazon.com/Ralph-Lauren-Women-Toilette-Natural/dp/B000C1W3OS/', # 8
'https://www.amazon.com/masatow-Women-Pheromone-Perfume-Roll/dp/B0C746QXL1/', # 9
'https://www.amazon.com/Michael-Kors-Wonderlust-Parfum-Spray/dp/B00RK1C3AW/')
```


```{r}
scrape_reviews <- function(url) {
session <- bow(url, user_agent = "Educational")
review_page <- scrape(session)

product_name <- review_page %>%
html_nodes('span#productTitle') %>%
html_text() %>%
trimws()

reviewers <- review_page %>%
html_nodes('.a-profile-name') %>%
html_text()

review_dates <- review_page %>%
html_nodes('.a-size-base.a-color-secondary.review-date') %>%
html_text()
review_dates_clean <- gsub("Reviewed in [a-zA-Z ]+ on ", "", review_dates)

review_titles <- review_page %>%
html_nodes('.review-title') %>%
html_text()
review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

verified_purchase <- review_page %>%
html_nodes('span[data-hook="avp-badge-linkless"]') %>%
html_text()

review_texts <- review_page %>%
html_nodes('div[data-hook="review-collapsed"] span') %>%
html_text() %>%
trimws()

max_length <- max(
length(reviewers),
length(review_dates_clean),
length(review_titles_clean),
length(review_texts),
length(verified_purchase),
na.rm = TRUE
)

product_name <- rep(product_name, length.out = max_length)
reviewers <- c(reviewers, rep(NA, max_length - length(reviewers)))
review_dates_clean <- c(review_dates_clean, rep(NA, max_length - length(review_dates_clean)))
review_titles_clean <- c(review_titles_clean, rep(NA, max_length - length(review_titles_clean)))
review_texts <- c(review_texts, rep(NA, max_length - length(review_texts)))
verified_purchase <- c(verified_purchase, rep(NA, max_length - length(verified_purchase)))

reviews <- data.frame(
Product = product_name,
Reviewer = reviewers,
Date = review_dates_clean,
ReviewTitle = review_titles_clean,
ReviewText = review_texts,
VerifiedPurchase = verified_purchase,
stringsAsFactors = FALSE
)

return(reviews)
}

all_reviews <- lapply(product_urls, scrape_reviews)

reviews_df <- bind_rows(all_reviews)

print(reviews_df)
```
```{r}
product_urls <- c( 'https://www.amazon.com/Oral-B-iO-Electric-Toothbrush-Rechargeable/dp/B0B5HRWH1S/', #1
'https://www.amazon.com/Oral-B-Rechargeable-Toothbrush-Intelligence-Replacement/dp/B084PPRXB5/', #2
'https://www.amazon.com/Oral-B-iO-Electric-Toothbrush-Rechargeable/dp/B0B5HVM6JX/', #3
'https://www.amazon.com/AquaSonic-Black-Ultra-Whitening-Toothbrush/dp/B072YVWBXH/', # 4
'https://www.amazon.com/Philips-Sonicare-Toothbrush-Rechargeable-HX3681/dp/B09LD7WRVS/', # 5
'https://www.amazon.com/Philips-Sonicare-ProtectiveClean-Rechargeable-HX6423/dp/B084TM4XKG/', #6
'https://www.amazon.com/Oral-B-Health-Soft-Toothbrushes-Count/dp/B01KZ6V00W/', #7
'https://www.amazon.com/Oral-B-1000-Rechargeable-Electric-Toothbrush/dp/B003UKM9CO/', # 8
'https://www.amazon.com/Oral-B-Bristles-Vivid-Toothbrush-White/dp/B06XK2M3H3/', # 9
'https://www.amazon.com/Colgate-Charcoal-Toothbrushes-Bristles-Surface/dp/B0BQPSB3GG/')
```


```{r}
scrape_reviews <- function(url) {
session <- bow(url, user_agent = "Educational")
review_page <- scrape(session)

product_name <- review_page %>%
html_nodes('span#productTitle') %>%
html_text() %>%
trimws()

reviewers <- review_page %>%
html_nodes('.a-profile-name') %>%
html_text()

review_dates <- review_page %>%
html_nodes('.a-size-base.a-color-secondary.review-date') %>%
html_text()
review_dates_clean <- gsub("Reviewed in [a-zA-Z ]+ on ", "", review_dates)

review_titles <- review_page %>%
html_nodes('.review-title') %>%
html_text()
review_titles_clean <- gsub("\\d+\\.\\d+ out of 5 stars", "", review_titles)
review_titles_clean <- trimws(review_titles_clean)

verified_purchase <- review_page %>%
html_nodes('span[data-hook="avp-badge-linkless"]') %>%
html_text()

review_texts <- review_page %>%
html_nodes('div[data-hook="review-collapsed"] span') %>%
html_text() %>%
trimws()

max_length <- max(
length(reviewers),
length(review_dates_clean),
length(review_titles_clean),
length(review_texts),
length(verified_purchase),
na.rm = TRUE
)

product_name <- rep(product_name, length.out = max_length)
reviewers <- c(reviewers, rep(NA, max_length - length(reviewers)))
review_dates_clean <- c(review_dates_clean, rep(NA, max_length - length(review_dates_clean)))
review_titles_clean <- c(review_titles_clean, rep(NA, max_length - length(review_titles_clean)))
review_texts <- c(review_texts, rep(NA, max_length - length(review_texts)))
verified_purchase <- c(verified_purchase, rep(NA, max_length - length(verified_purchase)))

reviews <- data.frame(
Product = product_name,
Reviewer = reviewers,
Date = review_dates_clean,
ReviewTitle = review_titles_clean,
ReviewText = review_texts,
VerifiedPurchase = verified_purchase,
stringsAsFactors = FALSE
)

return(reviews)
}

all_reviews <- lapply(product_urls, scrape_reviews)

reviews_df <- bind_rows(all_reviews)

print(reviews_df)
```


